### ISSUE TITLE
Whitelist should accept @domain.com

### ISSUE THREAD

**Issue by verberktstan** [brightin/mail_whitelist#3]
It would be a great improvement if the whitelist could contain domains. E.g. `["@brightin.nl"]` would accept ALL mailaddresses that contain `@brightin.nl`

Currently the check happens with `.include?` so it only checks if a mailaddress is an exact match / included in the whitelist array.

Maybe use `.in?` on every item in the whitelist?

**Comment by tomkr** [comment]
Fixed in #4.
